//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShope
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int oid { get; set; }
        public int idmenu { get; set; }
        public int number { get; set; }
        public int priceamount { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
